#include "car.h"
//P1.2--4 P1.3--3 P1.4--2 P1.5--1
void goFront(uint16_t speed){
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_1, GPIO_PORT_P1, GPIO_PIN2, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_2, GPIO_PORT_P1, GPIO_PIN3, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_3, GPIO_PORT_P1, GPIO_PIN4, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_4, GPIO_PORT_P1, GPIO_PIN5, 100, 0);
}

void goBack(uint16_t speed){
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_1, GPIO_PORT_P1, GPIO_PIN2, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_2, GPIO_PORT_P1, GPIO_PIN3, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_3, GPIO_PORT_P1, GPIO_PIN4, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_4, GPIO_PORT_P1, GPIO_PIN5, 100, speed);
}

void goLeft(uint16_t speed){
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_1, GPIO_PORT_P1, GPIO_PIN2, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_2, GPIO_PORT_P1, GPIO_PIN3, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_3, GPIO_PORT_P1, GPIO_PIN4, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_4, GPIO_PORT_P1, GPIO_PIN5, 100, speed);
}

void goRight(uint16_t speed){
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_1, GPIO_PORT_P1, GPIO_PIN2, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_2, GPIO_PORT_P1, GPIO_PIN3, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_3, GPIO_PORT_P1, GPIO_PIN4, 100, speed);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_4, GPIO_PORT_P1, GPIO_PIN5, 100, 0);
}

void goStop(){
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_1, GPIO_PORT_P1, GPIO_PIN2, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_2, GPIO_PORT_P1, GPIO_PIN3, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_3, GPIO_PORT_P1, GPIO_PIN4, 100, 0);
    PwmIntA(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_4, GPIO_PORT_P1, GPIO_PIN5, 100, 0);
}
